name: Regenerate resource files

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: pnpm install
      - name: Regenerate data
        run: pnpm start
      - name: Commit new files
        run: |
          git config --global user.email "noreply@example.com"
          git config --global user.name "Automated Data Update"
          git commit -a -m "Generate data stores"
          git push
